image: python:3.9

before_script:
  - python -V  # Print out python version for debugging
  - pip install pdm

stages:
  - Build
  - Test
  - Documentation
  - Deploy

test:
  stage: Test
  script:
    - pip install tox flake8
    # stop the build if there are Python syntax errors or undefined names
    - pdm run flake8 ./nvcl_kit --count --select=E9,F63,F7,F82 --show-source --statistics
    # exit-zero treats all errors as warnings
    - pdm run flake8 ./nvcl_kit --count --exit-zero --max-complexity=20 --max-line-length=127 --statistics
    - pdm run tox
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build:
  stage: Build
  script: 
    - pdm install
    - pdm build
  artifacts:
    paths:
      - dist/*.whl

pages:
  stage: Documentation
  script:
    - pip install sphinx sphinx-rtd-theme owslib shapely geojson
    - cd doc ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: Deploy
  script:
    - pip install twine
    - echo "$PYPI_CONFIG" > "/root/.pypirc"
    - pdm install
    - pdm build
    - pdm run twine upload --repository pypi dist/*
  only:
    - tags
