image: python:3.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - Build
  - Test
  - Documentation
  - Deploy

test:
  stage: Test
  script:
    - pip3 install tox flake8
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    # exit-zero treats all errors as warnings
    - flake8 . --count --exit-zero --max-complexity=20 --max-line-length=127 --statistics
    - tox

build:
  stage: Build
  script:
    - python3 setup.py bdist_wheel
    # run the command here
  artifacts:
    paths:
      - dist/*.whl

pages:
  stage: Documentation
  script:
    - pip3 install sphinx sphinx-rtd-theme owslib shapely
    - cd doc ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: Deploy
  script:
    - pip3 install twine
    - echo "$PYPI_CONFIG" > "/root/.pypirc"
    - python3 setup.py sdist bdist_wheel
    - twine upload --repository nexus dist/*.whl
    - twine upload --repository pypi dist/*
  only:
    - tags
