image: python:3.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - Build
  - Test
  - Documentation
  - Deploy

test:
  stage: Test
  script:
    - pip install tox
    - tox

build:
  stage: Build
  script:
    - python setup.py bdist_wheel
    # run the command here
  artifacts:
    paths:
      - dist/*.whl

documentation:
  stage: Documentation
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: Deploy
  script:
    - pip install twine
    - echo "$PYPI_CONFIG" > "/root/.pypirc"
    - python setup.py sdist bdist_wheel
    - twine upload --repository pypi dist/*
  only:
    - tags
