name: nvcl_kit build, test, pages & deploy
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.3.0
    - run: python -V
    - run: pip install pdm
    - run: pdm install
    - run: pdm build
    - uses: actions/upload-artifact@v4.6.2
      if: success()
      with:
        name: python-package-distributions
        path: dist/
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.3.0
    - uses: actions/download-artifact@v5
    - run: python -V
    - run: pip install pdm
    - run: pip install tox flake8
    - run: pdm run flake8 ./nvcl_kit --count --select=E9,F63,F7,F82 --show-source --statistics
    - run: pdm run flake8 ./nvcl_kit --count --exit-zero --max-complexity=20 --max-line-length=127 --statistics
    - run: pdm run tox
    # TODO: 'coverage' 
  pages:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    if: github.ref == 'refs/heads/master' || (startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.'))
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.3.0
    - run: python -V
    - run: apt-get update && apt-get install -y rsync
    - run: pip install pdm
    - run: pip install sphinx sphinx-rtd-theme owslib shapely geojson
    - run: cd doc ; make html; mv _build/html/ ../public/
    - uses: actions/upload-artifact@v4.6.2
      if: success()
      with:
        name: "${{ github.job }}"
        path: public
    - uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        branch: gh-pages
        folder: public
  deploy:
    name: Publish distribution to pypi
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')
    needs: pages
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment:
      name: pypi
      url: https://pypi.org/p/nvcl_kit
    permissions:
      id-token: write
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v5
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
